### ISSUE TITLE
TODO: Improve swap failure behaviors

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#56]
Preliminary thoughts regarding swap failure handling.

```
2022-05-18T08:35:35.984Z INFO    plugin-peerswap-plugin: [Swap:22fb1198c48b5b256429051aecba3b4c8c075787090dc5636174936b44ca97e1] Start new swap out: peer: REDACTED1 chanId: 717453x157x1 initiator: REDACTED2 amount 5365705
2022-05-18T08:35:43.786Z INFO    plugin-peerswap-plugin: [Swap:22fb1198c48b5b256429051aecba3b4c8c075787090dc5636174936b44ca97e1] Paid Feeinvoice of 438 sats
2022-05-18T09:02:14.840Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=1 still in progress, cannot retry before that completes., retry...
2022-05-18T09:02:14.905Z INFO    plugin-peerswap-plugin: 11:02:14 lightning.go:1271: unexpected end of JSON input
2022-05-18T09:02:24.592Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=1 still in progress, cannot retry before that completes., retry...
2022-05-18T09:02:34.591Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=1 still in progress, cannot retry before that completes., retry...
2022-05-18T09:02:44.599Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=1 still in progress, cannot retry before that completes., retry...
2022-05-18T09:02:54.598Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=1 still in progress, cannot retry before that completes., retry...
2022-05-18T09:03:04.590Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=1 still in progress, cannot retry before that completes., retry...
2022-05-18T09:03:14.588Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=1 still in progress, cannot retry before that completes., retry...
2022-05-18T09:03:24.588Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=1 still in progress, cannot retry before that completes., retry...
2022-05-18T09:03:43.920Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=2 still in progress, cannot retry before that completes., retry...
2022-05-18T09:03:43.920Z INFO    plugin-peerswap-plugin: 11:03:43 lightning.go:1271: unexpected end of JSON input
2022-05-18T09:03:44.590Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=2 still in progress, cannot retry before that completes., retry...
2022-05-18T09:03:54.592Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=2 still in progress, cannot retry before that completes., retry...
2022-05-18T09:04:04.586Z INFO    plugin-peerswap-plugin: error trying to pay invoice: 200:Payment with groupid=2 still in progress, cannot retry before that completes., retry...
2022-05-18T09:04:04.587Z INFO    plugin-peerswap-plugin: [FSM] Action failure could not pay invoice, last err 200:Payment with groupid=2 still in progress, cannot retry before that completes.
2022-05-18T09:04:04.592Z INFO    plugin-peerswap-plugin: [Swap:22fb1198c48b5b256429051aecba3b4c8c075787090dc5636174936b44ca97e1] Swap claimed cooperatively
```

#55 exposed multiple issues.

- [ ] PeerSwap generally needs to know all error messages from CLN and LND to be able to distinguish fatal errors from expected temporary problems.
- [ ] The above is an actual error caused by PeerSwap using the CLN API improperly. In this case it is fatal and it should give up quickly. In such fatal situations it correctly goes to `State_ClaimedCoop`.
- [ ] There exist some errors that are occasionally expected and temporary. In such cases PeerSwap should recognize and have a retry plan where it doesn't spam the log and it doesn't give up as quickly as two minutes. One such example is where the channel balance changed since the swap began but before the onchain transaction gained enough onchain confirmations. There may be other non-fatal temporary errors.

**Comment by wtogami** [comment]
we haven't had problems like this for a long time, closing
